services:
  chromadb:
    image: chromadb/chroma:0.4.14
    volumes:
      - ./local-recall-vector-db:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma # this is the default path, change it as needed
      - ANONYMIZED_TELEMETRY=FALSE
    ports:
      - 8000:8000
    networks:
      - net

  zookeeper-1:
    image: confluentinc/cp-zookeeper:7.6.0
    hostname: zookeeper-1
    container_name: zookeeper-1

    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      KAFKA_JMX_PORT: 10001
      KAFKA_JMX_HOSTNAME: localhost
      ZOOKEEPER_SERVERS: zookeeper-1:2888:3888
    cap_add:
      - NET_ADMIN
    ports:
      - 2181:2181
      - 10001:10001
      - 10101:8091

  kafka-1:
    image: confluentinc/cp-server:7.6.0
    hostname: kafka-1
    container_name: kafka-1

    healthcheck:
      test: curl -fail --silent http://kafka-1:8090/kafka/v3/clusters/ --output /dev/null || exit 1
      interval: 10s
      retries: 10
      start_period: 20s
    depends_on:
      - zookeeper-1
    environment:
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LISTENERS: PLAINTEXT://kafka-1:19091, EXTERNAL://0.0.0.0:9091
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:19091, EXTERNAL://localhost:9091
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_JMX_PORT: 10002
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_BROKER_RACK: rack-0
      KAFKA_MIN_INSYNC_REPLICAS: 1
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_CLUSTER_LINK_ENABLE: False
      KAFKA_CONFLUENT_REPORTERS_TELEMETRY_AUTO_ENABLE: False
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181
      KAFKA_CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      KAFKA_CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: kafka-1:19091
    cap_add:
      - NET_ADMIN
    ports:
      - 9091:9091
      - 10002:10002
      - 10102:8091
      - 10201:8090

networks:
  net:
    driver: bridge

volumes:
  local-recall-vector-db:
    driver: local
