services:
  chromadb:
    image: chromadb/chroma:0.4.14
    volumes:
      - ./local-recall-vector-db:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma # this is the default path, change it as needed
      - ANONYMIZED_TELEMETRY=FALSE
    ports:
      - 8000:8000
    networks:
      - net

networks:
  net:
    driver: bridge
volumes:
  local-recall-vector-db:
    driver: local
