services:
  chromadb:
    image: chromadb/chroma:0.4.14
    volumes:
      - ./local-recall-vector-db:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma # this is the default path, change it as needed
      - ANONYMIZED_TELEMETRY=FALSE
    ports:
      - 8000:8000
    networks:
      - net

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      ALLOW_ANONYMOUS_LOGIN: 'yes'
    networks:
      - net

  kafka:
    image: 'bitnami/kafka:latest'
    hostname: kafka
    container_name: kafka
    user: root
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: '1'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
    networks:
      - net
    depends_on:
      - zookeeper

  kafka-ui:
    container_name: kafka-ui
    depends_on:
      - kafka
      - zookeeper
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8080:8080
    networks:
      - net
    environment:
      KAFKA_CLUSTERS_0_NAME: local-recall
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
      DYNAMIC_CONFIG_ENABLED: true

networks:
  net:
    driver: bridge

volumes:
  local-recall-vector-db:
    driver: local
  kafka-ui:
    driver: local
